[pytest]
testpaths = selenium_tests/tests security_tests appium_tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = --verbose --html=reports/html/report.html --self-contained-html
